Feature: Batch file validation for MPSA_Cross Sell RS21097
#  Properties	          Description	               Mandatory(Y/N)	PegaSource	DatabaseTable	    Database Field	                           Comments
#  .CUST_ID	             Customer ID	                Y	             Database	CUST_DIM	        CIS_CUST_ID
#  .PRIM_EMAIL_ADDR	     Email Address	                Y	             Database	CUST_DIM	        PRIM_EMAIL_ADDR
#  .INDV_TTL_NM	         Individual Title	            N	             Database	CUST_DIM	        INDV_TTL_NM
#  .INDV_FRST_NM	     Individual First Name	        Y	             Database	CUST_DIM	        INDV_FRST_NM
#  .INDV_LAST_NM	     Individual Last Name	        N	             Database	CUST_DIM	        INDV_LAST_NM
#  .LanguageCode	     Language Code	                Y	             Database	CUST_DIM	        LANG_CD	Format:                         Uppercase first letter (i.e. 'E')
#  .OfferExpiry	         Offer expiry date	            N	             Database 	ACCT_DIM	        CLI_OFR_EXP_DT  	                    Earliest expiry from all eligible customer/account. Example: 20200506 (need to remove dashes
#                               +
#                           Strategy
#  Offer Code	         OfferID (pyName)	            Y	             Action	    pyName	            Last 4 digits (remove 'CIE')
#  Campaign Code	     Campaign code	                Y	             Action	    Campaign Code
#  .CreativeID	         CreativeID	                    Y	             Action  	Creative ID		                                            Default will be from Action. Strategy can overwrite if there is segmentation logic.
#                           or
#                         Strategy
#  .pxInteractionID	     Pega's Interaction ID	        Y	             Strategy	Foundation
#  Response tracking code Pega's Response tracking code	Y	             Strategy	Foundation	        InteractionID+'_'pyName
#  Mail ID	             Mail ID	                    N	             Strategy	Unique Number		                                        Need to be the same as DM file
#                                                                                      starting from
#                                                                                      2 Alpha characters
#                                                                                      + 6 Numeric values
#  .EmailSpecificText	    Email Specific Text (Name / Value pair)
#  Example: “AcctNum:” + .ACCT_NUM + “|LastName:”+”.INDV_LAST_NM+”|AcctBal:”+.ACCT_BAL_AMT


  @MPSACrossSellEmail @MPSACrossSellEmail_DatFile_Positive_Validation_5467 @5467 @EMAIL @RS21097 @AUTOTESTTOTAL#106
  Scenario Outline: MPSA CrossSellEmail_RS21097_5467_EMAIL Validate batch file details against database and pega for Positive test cases
    Given load data from "MPSACrossSell" excel sheet
    Given read batch file customer information details from excel sheet "CUST_DIM" for "<Test cases>"
    When read account information details from excel sheet "ACCT_DIM" for "<Test cases>"
    And read "mpsacrosssell" extract file with batch "bonus_interest;upto_interest;offer_months;regular_interest_rate;premium_period_interest_rate;offer_duration_days;mass_offer_start_date;mass_offer_end_date;" Email Specific Text Header
    And the user navigates to pega url
    When the user enters user name, password and click on login in pega Login screen
    And click on interaction History by customer link
    And click on actions and run in interactions history By customer screen
    And click on period link and clear today value
    And enter customer id in ih by customer screen and get IH table data
    Then validate MPSA CrossSell offer details in batch file against database and pega
    Examples:
      | Test cases                                                                                                                                                                                                                                                                          |
      | 5467_EMAIL_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_CONTROL and CURR_VAL!=1                                                                                                                                                                                                                |
      | 5467_EMAIL_05_07_With Ultimate And Preferred Accounts_MCB_IND != Y                                                                                                                                                                                                                  |
      | 5467_EMAIL_05_07_With Ultimate And Preferred Accounts_MCB_IND = Y                                                                                                                                                                                                                   |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1  OR CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL = 1                                                                                                                |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1  OR CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1                                                                                                                |
      | 5467_CUST_INSIGHTS.INSIGHT_CD =FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1)  AND CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL < 1                                                                                                               |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL! = 1)  OR CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1)                                                                                                             |
      | 5467_EMAIL_05_Creative_Not Auto-Enrolled with Ultimate Account_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_TARGET and CURR_VAL != 1                                                                                                                                                           |
      | 5467_EMAIL_06_Creative_Not Auto-Enrolled with MCB Preferred Account_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_TARGET and CURR_VAL != 1                                                                                                                                                      |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_TARGET and CURR_VAL != 1                                                                                                                                                          |
      | 5467_EMAIL_08_Creative_Not Auto-Enrolled with Other no Ultimate-Preferred_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_TARGET and CURR_VAL != 1                                                                                                                                                |
      | 5467_SRC_SYS_PRD_CD != BSAMP and ACCT_SUBSYS_ID = UF and  SRC_ACCT_STAT_CD = Active                                                                                                                                                                                                 |
      | 5467_SRC_SYS_PRD_CD = BSAMP  and ACCT_SUBSYS_ID != UF and SRC_ACCT_STAT_CD = Active                                                                                                                                                                                                 |
      | 5467_SRC_SYS_PRD_CD = BSAMP and ACCT_SUBSYS_ID = UF and SRC_ACCT_STAT_CD != Active                                                                                                                                                                                                  |
      | 5467_EMAIL_05_Creative_Not Auto-Enrolled with Ultimate Account                                                                                                                                                                                                                      |
      | 5467_EMAIL_06_Creative_Not Auto-Enrolled with MCB Preferred Account                                                                                                                                                                                                                 |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account                                                                                                                                                                                                                     |
      | 5467_EMAIL_08_Creative_Not Auto-Enrolled with Other no Ultimate-Preferred                                                                                                                                                                                                           |
      | 5467_EMAIL_05_Creative_Not Auto-Enrolled with Ultimate Account And ACCT_SUBSYS_ID != BB                                                                                                                                                                                             |
      | 5467_EMAIL_05_Creative_Not Auto-Enrolled with Ultimate Account And SRC_ACCT_STAT_CD != A                                                                                                                                                                                            |
      | 5467_EMAIL_05_Creative_Not Auto-Enrolled with Ultimate Account And PRIMARY_ACCT_HOLDER_FLAG != Y                                                                                                                                                                                    |
      | 5467_EMAIL_06_Creative_Not Auto-Enrolled with MCB Preferred Account And ACCT_SUBSYS_ID != BB                                                                                                                                                                                        |
      | 5467_EMAIL_06_Creative_Not Auto-Enrolled with MCB Preferred Account And SRC_ACCT_STAT_CD != A                                                                                                                                                                                       |
      | 5467_EMAIL_06_Creative_Not Auto-Enrolled with MCB Preferred Account And PRIMARY_ACCT_HOLDER_FLAG != Y                                                                                                                                                                               |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account And ACCT_SUBSYS_ID != BB                                                                                                                                                                                            |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account And SRC_ACCT_STAT_CD != A                                                                                                                                                                                           |
      | 5467_EMAIL_07_Creative_Not Auto-Enrolled with Preferred Account And PRIMARY_ACCT_HOLDER_FLAG != Y                                                                                                                                                                                   |
      | 5467_EMAIL_08_Creative_Not Auto-Enrolled with Other no Ultimate-Preferred And ACCT_SUBSYS_ID != BB                                                                                                                                                                                  |
      | 5467_EMAIL_08_Creative_Not Auto-Enrolled with Other no Ultimate-Preferred And SRC_ACCT_STAT_CD != A                                                                                                                                                                                 |
      | 5467_EMAIL_08_Creative_Not Auto-Enrolled with Other no Ultimate-Preferred And PRIMARY_ACCT_HOLDER_FLAG != Y                                                                                                                                                                         |
      | 5467_MK_BK_OFFERS_EMAIL_F = Y                                                                                                                                                                                                                                                       |
      | 5467_MK_BK_OFFERS_EMAIL_F = NULL                                                                                                                                                                                                                                                    |
      | 5467_PHYSICIANS_F = NULL                                                                                                                                                                                                                                                            |
      | 5467_MD_FINANCIAL_F = NULL                                                                                                                                                                                                                                                          |
      | 5467_ITRADE_MCLEOD_F = NULL                                                                                                                                                                                                                                                         |
      | 5467_DEDICATED_INVSTMNT_ADVISOR_F = NULL                                                                                                                                                                                                                                            |
      | 5467_ACCT_ODT = NULL                                                                                                                                                                                                                                                                |
      | 5467_PRD CD = 01 SUB PRD CD = 07                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = 02 SUB PRD CD = 05                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = 19 SUB PRD CD = 05                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = 13 SUB PRD CD = 05                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = 07 SUB PRD CD = 01                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = 23 SUB PRD CD = 02                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = VGD SUB PRD CD= AB                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = VCL SUB PRD CD= BC                                                                                                                                                                                                                                                    |
      | 5467_PRD CD = VLR SUB PRD CD= CD                                                                                                                                                                                                                                                    |
      | 5467_SRC_ACCT_STAT_CD! =  A                                                                                                                                                                                                                                                         |
      | 5467_SRC_ACCT_STAT_CD! = Open                                                                                                                                                                                                                                                       |
      | 5467_SRC_ACCT_STAT_CD = NULL                                                                                                                                                                                                                                                        |
      | 5467_CUST_TP_CD=PSNL,5467_Primary Country Cd = CA,5467_MRKTBLE_F = Y,5467_Customer Not Decease                                                                                                                                                                                      |
      | 5467_CUST_AGE >18                                                                                                                                                                                                                                                                   |
      | 5467_CUST_AGE=18                                                                                                                                                                                                                                                                    |
      | 5467_LANG_CD in small case_en                                                                                                                                                                                                                                                       |
      | 5467_LANG_CD in small case_fr                                                                                                                                                                                                                                                       |
      | 5467_DO_NOT_SOLICIT_F = NULL                                                                                                                                                                                                                                                        |
      | 5467_DO_NOT_EMAIL_F=N                                                                                                                                                                                                                                                               |
      | 5467_VLD_EML_F=Y                                                                                                                                                                                                                                                                    |
      | 5467_PRIM_EMAIL_ADDRESS!=NULL                                                                                                                                                                                                                                                       |
      | 5467_INDV_FRST_NM!=NULL/BLANK                                                                                                                                                                                                                                                       |
      | 5467_NOT_AML_KYC = N                                                                                                                                                                                                                                                                |
      | 5467_NOT_AML_KYC = NULL                                                                                                                                                                                                                                                             |
      | 5467_ACCT_ODT>90                                                                                                                                                                                                                                                                    |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1                                                                                                                                                                                                 |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA   and CUST_INSIGHTS.CURR_VAL > 1                                                                                                                                                                                                 |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA   and CUST_INSIGHTS.CURR_VAL = 1                                                                                                                                                                                                 |
      | 5467_PRD CODE=01  SUB PRD CD=01                                                                                                                                                                                                                                                     |
      | 5467_PRD CODE=VGD SUB PRD CD=NF                                                                                                                                                                                                                                                     |
      | 5467_PRD CODE=AXP SUB PRD CD=PC                                                                                                                                                                                                                                                     |
      | 5467_PRD CODE=VLR SUB PRD CD=RC                                                                                                                                                                                                                                                     |
      | 5467_PRD CODE=VFF SUB PRD CD=TR                                                                                                                                                                                                                                                     |
      | 5467_PRD CODE=VGD SUB PRD CD=RG                                                                                                                                                                                                                                                     |
      | 5467_INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days                                                                                                                                                                     |
      | 5467_INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days                                                                                                                                                                     |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days                                                                                  |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days                                                                                  |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days                                                                                    |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days                                                                                    |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days                                                                                    |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days                                                                                    |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE < 30 days |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL = 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days |
      | 5467_CUST_INSIGHTS.INSIGHT_CD = FLG_PAYROLL_INCREASE and CUST_INSIGHTS.CURR_VAL = 1 AND CUST_INSIGHTS.INSIGHT_CD = CNT_PAGEVISIT_HISA and CUST_INSIGHTS.CURR_VAL > 1 AND INSIGHT_CD = FLG_TAX_REFUND_DEPOSIT and CUST_INSIGHTS.CURR_VAL = 1 and CURRENT_DATE - EVENT_DATE = 30 days |
      | 5467_EMAIL_INSIGHT_CD = FLG_MPSA_ACQ_RS22021_TARGET and CURR_VAL!=1                                                                                                                                                                                                                 |
